<div class="row mb-3">
    <div class="col-12 mb-2">
        <div class="d-flex justify-content-between align-items-center gap-2">
            <div class="d-flex gap-1">
                <button class="btn btn-outline-primary btn-sm px-2" onclick="showCreateFolderSheet()">
                    <i class="bi bi-folder-plus"></i>
                </button>
                <button class="btn btn-primary btn-sm px-2" onclick="showUploadSheet()">
                    <i class="bi bi-plus-circle"></i>
                </button>
            </div>
            
            <div class="pagination-container d-flex align-items-center gap-1 flex-grow-1 justify-content-center" id="paginationContainer">
                <!-- Pagination will be generated by JavaScript -->
            </div>
            
            <div class="flex-shrink-0" style="min-width: 10px;">
                <select class="form-select form-select-sm" id="mobileFileType" style="border-radius: 0.5rem; border: 1px solid #d1d5db; font-size: 0.75rem;">
                    <option value="" style="padding: 0.25rem 0.5rem;">All</option>
                    <option value="pdf" style="padding: 0.25rem 0.5rem;">PDF</option>
                    <option value="doc" style="padding: 0.25rem 0.5rem;">Doc</option>
                    <option value="img" style="padding: 0.25rem 0.5rem;">Img</option>
                    <option value="video" style="padding: 0.25rem 0.5rem;">Vid</option>
                </select>
            </div>
        </div>
    </div>
</div>

<script>
function updatePaginationUI() {
    const container = document.getElementById('paginationContainer');
    if (!container) return;
    
    let html = '';
    
    if (currentPage > 1) {
        html += `<button class="min-w-[28px] h-7 flex items-center justify-center font-medium transition-all duration-200 ease-in-out px-2 py-1 text-xs border border-gray-300 rounded hover:bg-gray-50 hover:-translate-y-0.5" onclick="goToPage(${currentPage - 1})">
            <i class="bi bi-chevron-left"></i>
        </button>`;
    }
    
    let startPage = Math.max(1, currentPage - 3);
    let endPage = Math.min(lastPage, currentPage + 3);
    
    if (startPage > 1) {
        html += `<button class="min-w-[28px] h-7 flex items-center justify-center font-medium transition-all duration-200 ease-in-out px-2 py-1 text-xs border border-gray-300 rounded hover:bg-gray-50 hover:-translate-y-0.5" onclick="goToPage(1)">1</button>`;
        if (startPage > 2) {
            html += `<span class="px-1 text-gray-400">...</span>`;
        }
    }
    
    for (let i = startPage; i <= endPage; i++) {
        const isActive = i === currentPage;
        const activeClass = isActive ? 'bg-blue-500 text-white border-blue-500 shadow-md shadow-blue-500/30' : 'border-gray-300 hover:bg-gray-50 hover:-translate-y-0.5';
        html += `<button class="min-w-[28px] h-7 flex items-center justify-center font-medium transition-all duration-200 ease-in-out px-2 py-1 text-xs border rounded ${activeClass}" onclick="goToPage(${i})">${i}</button>`;
    }
    
    if (endPage < lastPage) {
        if (endPage < lastPage - 1) {
            html += `<span class="px-1 text-gray-400">...</span>`;
        }
        html += `<button class="min-w-[28px] h-7 flex items-center justify-center font-medium transition-all duration-200 ease-in-out px-2 py-1 text-xs border border-gray-300 rounded hover:bg-gray-50 hover:-translate-y-0.5" onclick="goToPage(${lastPage})">${lastPage}</button>`;
    }
    
    if (currentPage < lastPage) {
        html += `<button class="min-w-[28px] h-7 flex items-center justify-center font-medium transition-all duration-200 ease-in-out px-2 py-1 text-xs border border-gray-300 rounded hover:bg-gray-50 hover:-translate-y-0.5" onclick="goToPage(${currentPage + 1})">
            <i class="bi bi-chevron-right"></i>
        </button>`;
    }
    
    container.innerHTML = html;
}

function goToPage(page) {
    if (page >= 1 && page <= lastPage && page !== currentPage) {
        const url = new URL(window.location);
        url.searchParams.set('page', page);
        window.location.href = url.toString();
    }
}

function previousPage() {
    goToPage(currentPage - 1);
}

function nextPage() {
    goToPage(currentPage + 1);
}
</script>
