<?php

return [
    'default_role' => env('ACCESS_DEFAULT_ROLE', 'customer'),
    'default_department' => env('ACCESS_DEFAULT_DEPARTMENT', null),
    'assignment_strategy' => env('TICKET_AUTO_ASSIGN_STRATEGY', 'round_robin'),
    'ai_assisted_assignment' => (bool) env('ACCESS_AI_ASSIGNMENT', true),
    'max_workload' => (int) env('ACCESS_MAX_WORKLOAD', 25),
    'availability_blocks_assignment' => (bool) env('ACCESS_AVAILABILITY_BLOCKS', true),
    'assignable_availability' => ['available', 'busy'],
    'lockout_attempts' => (int) env('ACCESS_LOCKOUT_ATTEMPTS', 5),
    'lockout_minutes' => (int) env('ACCESS_LOCKOUT_MINUTES', 15),
    'session_timeout_minutes' => (int) env('ACCESS_SESSION_TIMEOUT', 120),
    'password_min_length' => (int) env('ACCESS_PASSWORD_MIN', 8),
    'password_require_mixed' => (bool) env('ACCESS_PASSWORD_MIXED', false),
    'mfa_required_for_staff' => (bool) env('ACCESS_MFA_STAFF', false),
    'day_shift_start' => env('ACCESS_DAY_SHIFT_START', '06:00'),
    'day_shift_end' => env('ACCESS_DAY_SHIFT_END', '18:00'),

    'super_admin_roles' => ['super_admin', 'administrator'],
    'super_admin_emails' => ['admin@aselco.ph'],

    'modules' => [
        'dashboard' => ['view'],
        'customers' => ['view', 'create', 'edit', 'delete', 'export'],
        'billing' => ['view'],
        'wallet' => ['view', 'create', 'approve', 'export'],
        'complaints' => ['view', 'create'],
        'tickets' => ['view', 'create', 'edit', 'assign', 'approve', 'export'],
        'chat' => ['view'],
        'notifications' => ['view'],
        'knowledge' => ['view', 'create', 'edit', 'delete'],
        'ai' => ['view', 'create', 'edit'],
        'reports' => ['view', 'export'],
        'users' => ['view', 'create', 'edit', 'assign', 'approve'],
        'departments' => ['view', 'create', 'edit'],
        'roles' => ['view', 'create', 'edit'],
        'permissions' => ['view', 'edit'],
        'settings' => ['view', 'edit'],
        'audit' => ['view', 'export'],
        'sessions' => ['view', 'edit'],
    ],

    /*
     * Canonical permission codes. Matrix cells map module + action → these codes.
     */
    'permissions' => [
        ['code' => 'dashboard.view', 'module' => 'dashboard', 'action' => 'view', 'name' => 'View dashboards'],
        ['code' => 'customers.view', 'module' => 'customers', 'action' => 'view', 'name' => 'View customers'],
        ['code' => 'customers.create', 'module' => 'customers', 'action' => 'create', 'name' => 'Create customers'],
        ['code' => 'customers.edit', 'module' => 'customers', 'action' => 'edit', 'name' => 'Edit customers'],
        ['code' => 'customers.delete', 'module' => 'customers', 'action' => 'delete', 'name' => 'Delete customers'],
        ['code' => 'customers.export', 'module' => 'customers', 'action' => 'export', 'name' => 'Export customers'],
        ['code' => 'billing.view', 'module' => 'billing', 'action' => 'view', 'name' => 'View billing'],
        ['code' => 'wallet.view', 'module' => 'wallet', 'action' => 'view', 'name' => 'View wallets'],
        ['code' => 'wallet.load', 'module' => 'wallet', 'action' => 'create', 'name' => 'Load wallets'],
        ['code' => 'wallet.approve', 'module' => 'wallet', 'action' => 'approve', 'name' => 'Approve wallet loads'],
        ['code' => 'wallet.transactions.view', 'module' => 'wallet', 'action' => 'view', 'name' => 'View wallet transactions'],
        ['code' => 'wallet.audit.view', 'module' => 'wallet', 'action' => 'export', 'name' => 'View wallet audit'],
        ['code' => 'complaints.view', 'module' => 'complaints', 'action' => 'view', 'name' => 'View complaints'],
        ['code' => 'complaints.create', 'module' => 'complaints', 'action' => 'create', 'name' => 'Create complaints'],
        ['code' => 'tickets.view', 'module' => 'tickets', 'action' => 'view', 'name' => 'View tickets'],
        ['code' => 'tickets.create', 'module' => 'tickets', 'action' => 'create', 'name' => 'Create tickets'],
        ['code' => 'tickets.edit', 'module' => 'tickets', 'action' => 'edit', 'name' => 'Edit tickets'],
        ['code' => 'tickets.assign', 'module' => 'tickets', 'action' => 'assign', 'name' => 'Assign tickets'],
        ['code' => 'tickets.reassign', 'module' => 'tickets', 'action' => 'assign', 'name' => 'Reassign tickets'],
        ['code' => 'tickets.escalate', 'module' => 'tickets', 'action' => 'assign', 'name' => 'Escalate tickets'],
        ['code' => 'tickets.close', 'module' => 'tickets', 'action' => 'approve', 'name' => 'Close tickets'],
        ['code' => 'tickets.export', 'module' => 'tickets', 'action' => 'export', 'name' => 'Export tickets'],
        ['code' => 'chat.view', 'module' => 'chat', 'action' => 'view', 'name' => 'Access customer support chat'],
        ['code' => 'notifications.view', 'module' => 'notifications', 'action' => 'view', 'name' => 'View notifications'],
        ['code' => 'knowledge.view', 'module' => 'knowledge', 'action' => 'view', 'name' => 'View knowledge'],
        ['code' => 'knowledge.create', 'module' => 'knowledge', 'action' => 'create', 'name' => 'Create knowledge'],
        ['code' => 'knowledge.edit', 'module' => 'knowledge', 'action' => 'edit', 'name' => 'Edit knowledge'],
        ['code' => 'knowledge.delete', 'module' => 'knowledge', 'action' => 'delete', 'name' => 'Delete knowledge'],
        ['code' => 'knowledge.publish', 'module' => 'knowledge', 'action' => 'edit', 'name' => 'Publish knowledge'],
        ['code' => 'knowledge.index', 'module' => 'knowledge', 'action' => 'edit', 'name' => 'Index knowledge'],
        ['code' => 'ai.chat', 'module' => 'ai', 'action' => 'view', 'name' => 'Use AI chat'],
        ['code' => 'ai.ticket-analysis.view', 'module' => 'ai', 'action' => 'view', 'name' => 'View AI ticket analysis'],
        ['code' => 'ai.response-suggestions', 'module' => 'ai', 'action' => 'create', 'name' => 'Generate AI replies'],
        ['code' => 'ai.knowledge.manage', 'module' => 'ai', 'action' => 'edit', 'name' => 'Manage AI knowledge'],
        ['code' => 'ai.settings.manage', 'module' => 'ai', 'action' => 'edit', 'name' => 'Manage AI settings'],
        ['code' => 'reports.view', 'module' => 'reports', 'action' => 'view', 'name' => 'View reports'],
        ['code' => 'reports.export', 'module' => 'reports', 'action' => 'export', 'name' => 'Export reports'],
        ['code' => 'users.view', 'module' => 'users', 'action' => 'view', 'name' => 'View users'],
        ['code' => 'users.create', 'module' => 'users', 'action' => 'create', 'name' => 'Create users'],
        ['code' => 'users.edit', 'module' => 'users', 'action' => 'edit', 'name' => 'Edit users'],
        ['code' => 'users.suspend', 'module' => 'users', 'action' => 'approve', 'name' => 'Suspend users'],
        ['code' => 'users.permissions.manage', 'module' => 'permissions', 'action' => 'edit', 'name' => 'Manage user permissions'],
        ['code' => 'departments.view', 'module' => 'departments', 'action' => 'view', 'name' => 'View departments'],
        ['code' => 'departments.create', 'module' => 'departments', 'action' => 'create', 'name' => 'Create departments'],
        ['code' => 'departments.edit', 'module' => 'departments', 'action' => 'edit', 'name' => 'Edit departments'],
        ['code' => 'roles.view', 'module' => 'roles', 'action' => 'view', 'name' => 'View roles'],
        ['code' => 'roles.create', 'module' => 'roles', 'action' => 'create', 'name' => 'Create roles'],
        ['code' => 'roles.edit', 'module' => 'roles', 'action' => 'edit', 'name' => 'Edit roles'],
        ['code' => 'permissions.view', 'module' => 'permissions', 'action' => 'view', 'name' => 'View permissions'],
        ['code' => 'settings.view', 'module' => 'settings', 'action' => 'view', 'name' => 'View access settings'],
        ['code' => 'settings.manage', 'module' => 'settings', 'action' => 'edit', 'name' => 'Manage access settings'],
        ['code' => 'audit.view', 'module' => 'audit', 'action' => 'view', 'name' => 'View audit logs'],
        ['code' => 'audit.export', 'module' => 'audit', 'action' => 'export', 'name' => 'Export audit logs'],
        ['code' => 'sessions.view', 'module' => 'sessions', 'action' => 'view', 'name' => 'View sessions'],
        ['code' => 'sessions.revoke', 'module' => 'sessions', 'action' => 'edit', 'name' => 'Revoke sessions'],
    ],

    'skills' => [
        'billing' => 'Billing',
        'metering' => 'Metering',
        'distribution' => 'Distribution',
        'transmission' => 'Transmission',
        'customer_service' => 'Customer Service',
        'account_assistance' => 'Account Assistance',
        'payment_assistance' => 'Payment Assistance',
        'technical_support' => 'Technical Support',
    ],
];
